name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        python3 manage.py test

        
  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build] 
    runs-on: ubuntu-latest   
    
    environment: 
      name: Development
      url: 'http://develop.serviceswebassahara.com'  
    steps:       
    - name: Remote SSH Commands      
      uses: fifsky/ssh-action@v0.0.5      
      with:
        command: |
          cd /home/hassan
          ls -a
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        user: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY}}
    - name: Deploy
      run: echo I am deploying!

  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://staging.serviceswebassahara.com'
    steps:    
    - name: Deploy
      run: echo I am deploying! 
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://serviceswebassahara.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
    
      
